on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Build image
        run: docker build -t docker.pkg.github.com/alphagov/gds-vale-styles/gds-vale:${GITHUB_REF}-${GITHUB_SHA::7} .
      - name: Publish image
        env:
          DOCKER_USER: vixus0
          DOCKER_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
        run: |
          docker login docker.pkg.github.com -u "$DOCKER_USER" -p "$DOCKER_TOKEN"
          docker push docker.pkg.github.com/alphagov/gds-vale-styles/gds-vale:${GITHUB_REF}-${GITHUB_SHA::7}
